# Generated by Django 3.0 on 2019-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
