# Generated by Django 3.0 on 2019-12-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='filename',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
